#pragma once

#if defined(KEYBOARD_beekeeb_piantor) && defined(UNICODEMAP_ENABLE)

enum icelandic_unicode_names {
    ISU_THORN_LOWER,
    ISU_THORN_UPPER,
    ISU_ETH_LOWER,
    ISU_ETH_UPPER,
    ISU_AE_LOWER,
    ISU_AE_UPPER,
    ISU_A_ACUTE_LOWER,
    ISU_A_ACUTE_UPPER,
    ISU_E_ACUTE_LOWER,
    ISU_E_ACUTE_UPPER,
    ISU_I_ACUTE_LOWER,
    ISU_I_ACUTE_UPPER,
    ISU_O_ACUTE_LOWER,
    ISU_O_ACUTE_UPPER,
    ISU_U_ACUTE_LOWER,
    ISU_U_ACUTE_UPPER,
    ISU_Y_ACUTE_LOWER,
    ISU_Y_ACUTE_UPPER,
    ISU_O_UMLAUT_LOWER,
    ISU_O_UMLAUT_UPPER,
};

#define IS_THORN    XP(ISU_THORN_LOWER, ISU_THORN_UPPER)
#define IS_ETH      XP(ISU_ETH_LOWER, ISU_ETH_UPPER)
#define IS_AE       XP(ISU_AE_LOWER, ISU_AE_UPPER)
#define IS_A_ACUTE  XP(ISU_A_ACUTE_LOWER, ISU_A_ACUTE_UPPER)
#define IS_E_ACUTE  XP(ISU_E_ACUTE_LOWER, ISU_E_ACUTE_UPPER)
#define IS_I_ACUTE  XP(ISU_I_ACUTE_LOWER, ISU_I_ACUTE_UPPER)
#define IS_O_ACUTE  XP(ISU_O_ACUTE_LOWER, ISU_O_ACUTE_UPPER)
#define IS_U_ACUTE  XP(ISU_U_ACUTE_LOWER, ISU_U_ACUTE_UPPER)
#define IS_Y_ACUTE  XP(ISU_Y_ACUTE_LOWER, ISU_Y_ACUTE_UPPER)
#define IS_O_UMLAUT XP(ISU_O_UMLAUT_LOWER, ISU_O_UMLAUT_UPPER)

#endif
